name: CI

on:
  push:
    branches:
      - master
jobs:
  code_quality:
    name: Psalm example
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: shivammathur/setup-php@2.3.1
        with:
          php-version: '7.4'
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Psalm
        run: ./vendor/bin/psalm --taint-analysis